config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :messages
root 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
 has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]

 def index
   @messages = Message.all.order("created_at DESC")
 end

 def show
 end

 def new
   @message = Message.new
 end

 def create
   @message = Message.new(message_params)
   if @message.save
    redirect_to root_path
   else
    render 'new'
   end
 end

 def edit
 end

 def update
   if @message.update(message_params)
    redirect_to message_path
   else
     render 'edit'
   end
 end

 def destroy
   @message.destroy
   redirect_to root_path
 end

 private

  def message_params
   params.require(:message).permit(:title, :description, :image)
  end 

  def find_message
   @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<%= link_to "Message Board", root_path, class: "navbar-brand" %>
</div>
<ul class="new navbar-nav">
<li><%= link_to "Sign Up", new_user_registration_path %></li>
<if user_signed_in? %>
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
<end>
     </ul>
    </div>
   </div>

  
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>



<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>

<div class= "field">
   <%= f.label :image %><br>
   <%= f.file_field :image %>
</div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
   <h2><%= message.title %></h2>
   <%= image_tag message.image.url(:thumb) %>
   <%= link_to "View Message", message_path(message), class: "btn btn-default" %>
   <% end %>
<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form' %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2> 
<p><%= @message.description %></p>
<p>
   <%= image_tag @message.image.url(:medium) %>
</p>

<%= link_to "Edit", edit_message_path(@message) %>
<%= link_to "Back", root_path %>
<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm:"Are you Sure?"} %>